export default tabs = {
  subCategories: {
    'Women\'s Fashion': [
      { text: 'Accessories', icon: 'basket2x' },
      { text: 'Activewear', icon: 'basket2x' },
      { text: 'Dresses', icon: 'basket2x' },
      { text: 'Handbags & purses', icon: 'basket2x' },
      { text: 'Jewelry & Watches', icon: 'basket2x' },
      { text: 'Skirts Jeans & Pants', icon: 'basket2x' },
      { text: 'Sleeperwear & intimates', icon: 'basket2x' },
      { text: 'Suits', icon: 'basket2x' },
      { text: 'Swimwear', icon: 'basket2x' },
      { text: 'Top', icon: 'basket2x' },
      { text: 'Women\'s Shoes', icon: 'basket2x' },
    ],
    'Men\'s Fashion': [
      { text: 'Activewear', icon: 'basket2x' },
      { text: 'Jewelry & Watches', icon: 'basket2x' },
      { text: 'Jeans & Pants', icon: 'basket2x' },
      { text: 'Men\'s Grooming', icon: 'basket2x' },
      { text: 'Men\'s Shoes', icon: 'basket2x' },
      { text: 'Shirts', icon: 'basket2x' },
      { text: 'Suits', icon: 'basket2x' },
      { text: 'Top', icon: 'basket2x' },
    ],
    'Kid\'s Fashion': [
      { text: 'Babies & Toddler', icon: 'basket2x' },
      { text: 'Boy\'s & Fashion', icon: 'basket2x' },
      { text: 'Girl\'s & Fashion', icon: 'basket2x' },
      { text: 'Kid\'s & Fashion', icon: 'basket2x' },
      { text: 'Toys & Hobbies', icon: 'basket2x' },
    ],
    'Shoes': [
      { text: 'Kid\'s & Shoes', icon: 'basket2x' },
      { text: 'Men\'s & Shoes', icon: 'basket2x' },
      { text: 'Women\'s & Shoes', icon: 'basket2x' },
    ],
    'Tech': [
      { text: 'Audio and TV', icon: 'basket2x' },
      { text: 'Computers & Tablets', icon: 'basket2x' },
      { text: 'Digital Cameras', icon: 'basket2x' },
      { text: 'Electronics', icon: 'basket2x' },
      { text: 'Phones & Wireless', icon: 'basket2x' },
    ],
    'Bags': [
      { text: 'Business', icon: 'basket2x' },
      { text: 'Handbags & Purses', icon: 'basket2x' },
      { text: 'Men\'s Wallets', icon: 'basket2x' },
    ],
    'Beauty & Health': [
      { text: 'Bath & Body', icon: 'basket2x' },
      { text: 'Cosmetics', icon: 'basket2x' },
      { text: 'Fragrance', icon: 'basket2x' },
      { text: 'Hair Care', icon: 'basket2x' },
      { text: 'Hair Salons', icon: 'basket2x' },
      { text: 'Men\'s Grooming', icon: 'basket2x' },
      { text: 'Skin Care', icon: 'basket2x' },
    ],
  },
  categories: [
    { text: 'All Store', icon: 'basket2x' },
    { text: 'Women\'s Fashion', icon: 'basket2x' },
    { text: 'Men\'s Fashion', icon: 'basket2x' },
    { text: 'Kid\'s Fashion', icon: 'basket2x' },
    { text: 'Bags', icon: 'basket2x' },
    { text: 'Beauty & Health', icon: 'basket2x' },
    { text: 'Books and Education', icon: 'basket2x' },
    { text: 'Department stores', icon: 'basket2x' },
    { text: 'Jewelry & watches', icon: 'basket2x' },
    { text: 'Luxury Retailers', icon: 'basket2x' },
    { text: 'Shoes', icon: 'basket2x' },
    { text: 'Sports', icon: 'basket2x' },
    { text: 'Tech', icon: 'basket2x' },
    { text: 'Toys & Hobbies', icon: 'basket2x' },
    { text: 'Auto Parts', icon: 'basket2x' },
    { text: 'Sports & Fitness', icon: 'basket2x' },
  ],
}
