export default [
    {
        name: 'AMAZON.COM',
        platformUrl: 'AMAZON.COM',
        id: 1
    },
    {
        name: 'AMAZON.CO.UK',
        platformUrl: 'AMAZON.CO.UK',
        id: 2
    },
    {
        name: 'MACYS.COM',
        platformUrl: 'MACYS.COM',
        id: 3
    },
    {
        name: '6PM.COM',
        platformUrl: '6PM.COM',
        id: 4
    },
    {
        name: 'FRAGRANCE DIRECT.CO.UK',
        platformUrl: 'facebook.com',
        id: 5
    },
    {
        name: 'PERFUME SHOP.COM',
        platformUrl: 'facebook.com',
        id: 6
    },
    {
        name: 'AMAZON.COM',
        platformUrl: 'AMAZON.COM',
        id: 7
    },
    {
        name: 'AMAZON.CO.UK',
        platformUrl: 'AMAZON.CO.UK',
        id: 8
    },
    {
        name: 'MACYS.COM',
        platformUrl: 'MACYS.COM',
        id: 9
    },
    {
        name: '6PM.COM',
        platformUrl: '6PM.COM',
        id: 10
    },
    {
        name: 'FRAGRANCE DIRECT.CO.UK',
        platformUrl: 'facebook.com',
        id: 11
    },
    {
        name: 'PERFUME SHOP.COM',
        platformUrl: 'facebook.com',
        id: 12
    },
//     1.AMAZON.COM 2.AMAZON.CO.UK
// 3.EBAY.COM
// 4.MACYS.COM
// 5.6PM.COM
// 6.FRAGRANCE DIRECT.CO.UK 7.PERFUME SHOP.COM 8.FRAGRANCE SHOP.COM 9.NEXT.CO.UK 10.NORDSTROM.COM 11.JOMASHOP.C0M
// 12.POLO RALPH LAUREN.COM 13.CARTERS.COM
// 14.OSHKOSH B’GOSH.COM 15.THE CHILDREN’S PLACE.COM 16.NUTS.COM
// 17.FROCUP.COM
// 18.UNIFORM WAREHOUSE.COM 19.WALMART.COM 20.NINEWEST.COM 21.BOOHOO.COM 22.EVERYTHING 5 POUNDS.COM 23.ASDA.COM
// 24.ALDO.COM
// LIST OF STORES
// 25.SPORT DIRECT.COM 26.NIKE.COM
// 27.BEST BUY.COM 28.B&H.COM 29.H&M.COM 30.FARFETCH.COM
// 31.MENS WAREHOUSE 32.AUTOZONE.COM 33.CARID.COM 34.PARCIFICAUTOCENTER.COM 35.WORLD OF WATCHES.COM 36.T.M LEWIN.CO.UK 37.DILLARDS.COM
// 38.SHOEZONE.COM 39.HP.COM
// 40.ARMANI EXCHANGE.COM 41.BEBE.COM
// 42.ALL BEAUTY.COM 43.CLINIQUE.COM
// 44.LOUIS VUITTON.COM 45.GUCCI.COM
// 46.DOLCE & GABBANA.COM
// 47.HAWES & CURTIS.CO.UK 48.JOHN LEWIS.COM
// 49.A1 SUPPLEMENT.COM 50.ACCESSORIZE.COM
// 51.AERIE.COM
// 52.AEROPOSTALE.COM
// 53.AMERICAN EAGLE OUTFITTERS.COM 54.GAP.COM
// 55.BANANA REPUBLIC.COM 56.ATHLETA GAP.COM 57.BARE NECESSITIES.COM 58.BATHS &BODY WORKS.COM 59.BROOKS BROTHERS.COM 60.BURTON.CO.UK 61.CHARLES TYRWHITT.COM 62.CLARKS.CO.UK 63.CLAIRE’S.COM 64.CLOTHING UNDER 10.COM 65.DOROTHY PERKINS.COM 66.EBONYLINE.COM 67.FRENCH TOAST.COM 68.KOHLS.COM
// 69.MARKS & SPENCER.COM 70.MAPLIN.CO.UK 71.MISGUIDED.CO.UK 72.MOTHERHOOD.COM 73.MR PORTER.COM
// 74.NEIMAN MARCUS.COM 75.NEIMAN MARCUS LAST CALL.COM
// 76.NEW EGG.COM 77.NEW LOOK.COM 78.OASIS-STORES.COM
// 79.OLD NAVY.GAP.COM 80.NORDSTROMRACK.COM 81.OVERSTOCK.COM
// 82.PARTY PACK.CO.UK 83.RIVERISLAND.COM
// 84.SELFRIDGES.COM 85.SHOEAHOLICS.COM 86.THOMOSPINK.COM
// 87.TILLYS.COM 88.TOPMAN.COM
// 89.TOPSHOP.COM 90.VICTORIASSECRET.COM 91.YANKEE CANDLES.COM 92.ZAPPOS.COM
// 93.EVANS.CO.UK 94.WALLIS.CO.UK
// 95.WOLF & BADGER.COM 96.WOLFORD.CO.UK
// 97.URBANOG.COM 98.FINOORA.CO.UK

// 99 .FIGLEAVES.COM 100.BUDGET GOLF.COM

]